# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-12 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredimage',
            name='img',
            field=models.ImageField(upload_to=''),
        ),
    ]
